image: rust:1

stages:
    - lint
    - build

rustfmt:
    stage: lint
    script:
        - rustup component add rustfmt
        - cargo fmt --all -- --check

clippy:
    stage: lint
    allow_failure: true
    script:
        - rustup component add clippy
        - cargo clippy --all-targets --all-features -- -D warnings

deny:
    stage: lint
    allow_failure: true
    script:
        - cargo install --locked cargo-deny
        - cargo deny init
        - cargo deny check

.build_steps:
    stage: build
    script:
        - rustup target add $target
        - cargo build --target=$target --release
        - cargo test --verbose
        - mkdir bin
        - mv ./target/release/comtrya ./bin/comtrya-$target
    artifacts:
        paths:
            - ./bin/comtrya-$target
        expire_in: 1 hour

x86-linux:
    extends: .build_steps
    variables:
        target: x86_64-unknown-linux-gnu

x86-darwin:
    extends: .build_steps
    variables:
        target: x86_64-apple-darwin

x86-windows:
    extends: .build_steps
    variables:
        target: x86_64-pc-windows-msvc

aarch64-linux:
    extends: .build_steps
    variables:
        target: aarch64-unknown-linux-gnu

aarch64-darwin:
    extends: .build_steps
    variables:
        target: aarch64-apple-darwin

aarch64-windows:
    extends: .build_steps
    variables:
        target: aarch64-pc-windows-msvc
