name: Release

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
